name: WORFLOW

on:
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Установить зависимости
        run: go mod tidy

      - name: Проверка формата кода
        run: go fmt ./...

      - name: Запустить тесты
        run: go test ./...
#pushing
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/parcel-tracker:${{ env.TAG }}"